# Generated by Django 4.1 on 2022-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
