# Generated by Django 4.1 on 2022-08-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('OP', 'Opened'), ('CA', 'Cancelled'), ('DA', 'Delivered')], max_length=2, null=True)),
                ('opened_time', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
